# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(help_text='First name of customer', max_length=30)),
                ('sName', models.CharField(help_text='Last name of customer', max_length=30)),
                ('address', models.CharField(help_text='Address of the customer', max_length=255)),
                ('phNumb', models.CharField(help_text='Phone number of customer', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
